[project]
authors = ["Edouard Duchesnay <edouard.duchesnay@cea.fr>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "pystatsml_labs"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
scikit-learn = ">=1.5.2,<2"
scipy = ">=1.14.1,<2"
pandas = ">=2.2.3,<3"
statsmodels = ">=0.14.4,<0.15"
seaborn = ">=0.13.2,<0.14"
ipykernel = ">=6.29.5,<7"
nbstripout = ">=0.7.1,<0.8"
